# Deploying a React App Using GitHub Pages and GitHub Actions | by Clyde D'Souza | codeburst - https://bit.ly/3bqJEvz
name: Build & deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install NPM packages
      run: yarn # npm ci

    - name: Build project
      run: npm run build

    - name: Run tests
      run: npm run test --if-present

    - name: Repair paths
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "/assets"
        replace: "./assets"
        include: "index.html"
        regex: false

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./dist

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
